
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: pytest
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/fullstackapp
      - SECRET_KEY=thisisasecretkey       
      - ALGORITHM=HS256
    ports:
      - "8000:8000"
    networks:
      - fullstackapp_network

networks:
  fullstackapp_network:
    driver: bridge
